name: Working with Debug logging

on:
    push:
    workflow_dispatch: 
env:
    user_1: foo-user
    user_2: bar-user
jobs:
    debug_job:
        runs-on: ubuntu-latest
        steps:
        - name: Step 1 - Checkout Repo
          uses: actions/checkout@v4

        - name: Step 2 - Set user1 as USERNAME
          run: | 
            echo "USERNAME = $user_1" >> $GITHUB_ENV

        - name: Step 3 - Printing USERNAME
          run: |
            echo "Printing USERNAME env variable from previous steps "
            echo "Username == $USERNAME" 
            exit 1

        - name: Step 4 - Printing USER_2
          run: echo "$user_2"
